name: Docker CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t node-app .

      - name: Run and Check
        run: |
          docker run -d -p 8080:3000 --name test_container node-app
          sleep 10
          docker logs test_container
          curl --verbose localhost:8080

